export type ErrorCode =
  | "FILE_TOO_LARGE"
  | "INVALID_PDF"
  | "PASSWORD_PROTECTED"
  | "MISSING_FILE"
  | "BUSY"
  | "COMPRESS_FAILED"
  | "COMPRESS_TIMEOUT"
  | "INTERNAL"
  | "EXPIRED"
  | "NETWORK";

export const ERROR_CODES: ReadonlySet<ErrorCode> = new Set<ErrorCode>([
  "FILE_TOO_LARGE",
  "INVALID_PDF",
  "PASSWORD_PROTECTED",
  "MISSING_FILE",
  "BUSY",
  "COMPRESS_FAILED",
  "COMPRESS_TIMEOUT",
  "INTERNAL",
  "EXPIRED",
  "NETWORK",
]);
